# Generated by Django 6.0.5 on 2026-06-11 13:03

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('system_slug', models.SlugField(max_length=100, unique=True, verbose_name='System Slug')),
                ('priority', models.CharField(choices=[('Low', 'Low Priority'), ('Medium', 'Medium Priority'), ('High', 'High Priority')], default='Low', max_length=10, verbose_name='Default Priority')),
                ('assignment_group', models.CharField(choices=[('Public Works', 'Public Works Department'), ('Animal Control', 'Animal Control'), ('Traffic Safety', 'Traffic Safety & Signaling'), ('Sanitation', 'Sanitation & Waste Management')], default='Public Work', max_length=50, verbose_name='Responsibe Municipal Group')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Group Description')),
            ],
            options={
                'verbose_name': 'Civic Issue Category',
                'verbose_name_plural': 'Civic Issue Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ticket Tracking Identifier')),
                ('title', models.CharField(max_length=150, verbose_name='Issue Title Summary')),
                ('description', models.TextField(verbose_name='Detailed Issue Description')),
                ('latitude', models.FloatField(verbose_name='Geospatial Longitude')),
                ('longitude', models.FloatField(verbose_name='Geospatial Longitude')),
                ('status', models.CharField(choices=[('Open', 'Open / Received'), ('Investigating', 'Under Investigation'), ('Scheduled', 'Work Scheduled'), ('In Progress', 'Work in Progress'), ('Resolved', 'Resolved & Closed'), ('Rejected', 'Rejected / Duplicate')], default='Open', max_length=20, verbose_name='Remediation Status')),
                ('automated_priority_override', models.BooleanField(default=False, verbose_name='AI Priority Override Elevated')),
                ('anonymous_reporter_hash', models.CharField(max_length=64, verbose_name='Anoymized Signature Hash')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='Upvote Verification Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.category', verbose_name='Issue Classification')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_issues', to=settings.AUTH_USER_MODEL, verbose_name='Reporting Citizen')),
            ],
            options={
                'verbose_name': 'Civic Issue Report',
                'verbose_name_plural': 'Civic Issue Reports',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.ImageField(upload_to=reports.models.get_attachment_upload_path, verbose_name='Uploaded Evidance Image')),
                ('file_size', models.IntegerField(default=0, verbose_name='Assest Size in Bytes')),
                ('mime_type', models.CharField(max_length=100, verbose_name='File Mime Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='reports.issuereport', verbose_name='Associated Ticket')),
            ],
            options={
                'verbose_name': 'Media Evidence Attachment',
                'verbose_name_plural': 'Media Evidence Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('Open', 'Open / Received'), ('Investigating', 'Under Investigation'), ('Scheduled', 'Work Scheduled'), ('In Progress', 'Work in Progress'), ('Resolved', 'Resolved & Closed'), ('Rejected', 'Rejected / Duplicate')], max_length=20, verbose_name='Previous State')),
                ('new_status', models.CharField(choices=[('Open', 'Open / Received'), ('Investigating', 'Under Investigation'), ('Scheduled', 'Work Scheduled'), ('In Progress', 'Work in Progress'), ('Resolved', 'Resolved & Closed'), ('Rejected', 'Rejected / Duplicate')], max_length=20, verbose_name='New State')),
                ('comment', models.TextField(blank=True, verbose_name='Citizen Comment')),
                ('administrative_notes', models.TextField(blank=True, verbose_name='Municipal Admin Comment')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='reports.issuereport', verbose_name='Linked Issue Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Status Log',
                'verbose_name_plural': 'Ticket Status Logs',
                'ordering': ['created_at'],
            },
        ),
    ]
